/** @type {import('tailwindcss').Config} */

module.exports = {
    content: ['./src/**/*.{ts,tsx,html,js}'],
    darkMode: 'class',
    theme: {
        screens: {md: '620px', tablet: '768px', breakpoint: '850px'},
        extend: {
            colors: {
                gray: {
                    100: '#f7f7f7',
                    300: '#cff0e0',
                    600: '#828282',
                    '100_01': '#f5f4f4',
                },
                blue: {500: '#1da1f2', A400: '#1877f2'},
                light_green: {100: '#ddfbc7'},
                light_blue: {50: '#ceeafc'},
                red: {100: '#ffd3e2'},
                lime: {100: '#f4f0cb'},
                green: {A700: '#15c370'},
                pink: {A400: '#e90d53'},
                blue_gray: {900: '#272d40'},
                white: {A700: '#ffffff'},
                black: {'900_26': '#00000026'},
                white: '#fff',
                borderGray: '#E2E2E2',
                textColor: '#282D41',
                alertRed: '#E2542C',
                blackMain: '#333333',
                blackSecondary: '#1C1B1F',
                paleGray: '#f7f7f7',
                inputBorderGray: '#7C7C7C',
                lineGray: '#838383',
                logoGreen: '#15C370',
                lightGreen: '#EFFFF8',
                activeChatGray: '#EEEEEE',
                badgeBlack: '#242136',
                cashGreen: '#9CF6B5',
                babyProductsGreen: '#65F5C5',
                linkBlue: '#6B91DB',
                review: '#B3E5B4',
                help: '#A0D6FF',
                service: '#FF9A9A',
                suggestion: '#FFFFB3',
                other: '#D3D3D3',
                emailBg: '#191621',
            },
            fontFamily: {
                opensans: 'Open Sans',
                quicksand: 'Quicksand',
                lato: 'Lato',
                mainSans: ['OpenReg', 'sans-serif'],
                lightSans: ['OpenLight', 'sans-serif'],
                boldSans: ['OpenBold', 'sans-serif'],
                mainQuick: ['QuicksandReg', 'sans-serif'],
                lightQuick: ['QuicksandLight', 'sans-serif'],
                boldQuick: ['QuicksandBold', 'sans-serif'],
                lato: ['Lato', 'sans-serif'],
            },

            fontSize: {
                xl: '32px',
                lg2: '28px',
                lg: '24px',
                md2: '20px',
                md: '18px',
                default: '16px',
                sm: '14px',
                sm2: '12px',
                xs: '10px',
                xs2: '8px',
            },
            borderRadius: {
                round: '50%',
                pill: '28px',
                medium: '8px',
            },
            boxShadow: {bs: '0px 2px  6px 2px #00000026'},
        },
    },
    plugins: [require('@tailwindcss/forms')],
};
