const chats = [
    {
        id: 1,
        name: 'Andrew',
        bgColor: '',
        isPackage: false,
        packageName: '',
        rating: '4.7',
        requestType: '#A0D6FF',
        requestText: 'Ask for help',
    },
    {
        id: 2,
        name: 'Alisa',
        bgColor: '#9CF6B5',
        isPackage: true,
        packageName: 'Cash',
        rating: '4.8',
        requestType: '#FF9A9A',
        requestText: 'Report a service problem',
    },
    {
        id: 3,
        name: 'Andrew',
        bgColor: '',
        isPackage: false,
        packageName: '',
        rating: '4.7',
        requestType: '#D3B6F3',
        requestText: 'Report a deal problem',
    },
    {
        id: 4,
        name: 'Alisa',
        bgColor: '#65F5C5',
        isPackage: true,
        packageName: 'Baby products',
        rating: '4.8',
        requestType: '#D3D3D3',
        requestText: 'Other',
    },
    {
        id: 5,
        name: 'Andrew',
        bgColor: '',
        isPackage: false,
        packageName: '',
        rating: '4.7',
        requestType: '',
        requestText: '',
    },
];

export default chats;
